### ISSUE TITLE
feature-request - configurable set-of-filters for exif-data-viewing

### ISSUE THREAD

**Issue by svilendobrev** [luebking/phototonic#66]
current exif-data is just a raw dump of any values that happen to be there. One has to scan through hundreds of things to find stuff.

It would be very convenient if there is a configurable set of filters over all that - what to see there (and a show-all-raw button for the brave).
* one filter for each semantical value - e,g. "aperture" may be named differently in different camera-makers. Just a list of (partial)texts to search for is okay . e.g. "resolution|dimensions" or "resolution dimensions" meaning search for any of these
* set of above - e.g. for aperture, iso, speed, resolution, datetime ..

every user usually has images of multiple - but limited number - of cameras, and can make a config to match all those.

`jhead` has somewhat reasonable output, but even that is too verbose in most cases.

**Comment by stefonarch** [comment]
I second that feature request :)

**Comment by svilendobrev** [comment]
making that a regex should be enough, as long it is saved somewhere. One can write very elaborate regexes :) Although the sorting of the filtered lines remains dependent on the raw-dump. Might just sort it alphabetical, and that's it.

p.s. As i said, my usage is strictly read-only. Moving/renaming files - yes, but not changing them. Even will be nice if saving can be somehow forbidden. But that's a too long stretch.

**Comment by luebking** [comment]
> One can write very elaborate regexes :)

Sure, but you don't want to write them in a 200px wide single-line, do you?

@stefonarch any take on this?
Would a set of variables like "$canon", "$nikon" "$aperture" (which you would still have to manually enter to control the filter) etc. be more useful than a single static global default filter? (All regexp, ie. that filter can match whatever it wants)

**Comment by stefonarch** [comment]
I've to look into my exiv data, but somehow something user friendly, like 2 or 3 levels? Full data, reduced (time, aperture, exposure, camera and few others)? No idea if that is doable though.

**Comment by luebking** [comment]
I've already implemented the histogram to be toggled into  a 32x20 icon on left clicks.
The filter applies a match, ie "color|orientation|date" will only show data matching those keys.
But oc. it's a regexp, so you can negate every filter - except that it's a regexp, so that's more involved ;)

```date|^(?!.*date).*$```
First part matches "date", second part matches everything not including "date"

**Comment by svilendobrev** [comment]
add one always-there option of "none" - in the filter-chooser

**Comment by svilendobrev** [comment]
how to hide the histogram?

**Comment by svilendobrev** [comment]
mmh. i want it hidden, and that to be remembered - part of the filter if you want.
then i want to tuck the window of image-props as a square under/above the file-system tall window, so they both make a column, like 50 letters wide. 
And all the rest is thumbnails.. and i still cannot lay as many quality thumbnails on a screen as i can put printed photos on my desk..
But anyway. Have fun :)

**Comment by luebking** [comment]
Sidebars:
1. since you're using a preview window, you're aware that you can display the exif info there (unfiltered, though there's some hardcoded stuff to filter out junk some cameras add - might be worthwhile to enhance this) - w/o a histogram
2. Some very early versions of phototonic (I've only ever seen old screenshots of that) seem to have used an irregular grid for the thumbnails.
This will have a performance hit but idk whether there were other reasons why that was abandoned. Might be worth some experiments.

Other than that, either get a bigger monitor or a smaller desk :P

**Comment by stefonarch** [comment]
Sorry for my absence, was busy with tons of other things, discovered now where the filter is :)
My use case is more pressing I in the viewer, mostly looking for creating time. Anyway, nice and the idea to move the windows to another screen didn't came to my mind but is very practical.

**Comment by luebking** [comment]
==>
> maybe the only good solution will be to have a (preset) "$preview" filter

??

**Comment by svilendobrev** [comment]
> Can you post some exif samples of images?

i have posted my filter above, covers quite a variety lot of cameras. e.g. FNumber is much more prominent than Aperture(Value), isospeedratings is more prominent that isospeed etc. Some models/makes have both and even more variants. Some do not have basic stuff like Make (or Model). So no silver bullet.
But yes, an editable $preview would be best ; gives max flexibility

**Comment by svilendobrev** [comment]
heh. if you tell me how to dump that image-info-view into text... it's only selectable line by line and copyable..

Here an image: https://www.svilendobrev.com/vodolet/2022-ipan13103.jpg
Download it and analyze..

this is from jhead:
```
$ jhead /home/tmp/2022-ipan13103.jpg 
File name    : /home/tmp/2022-ipan13103.jpg
File size    : 472489 bytes
File date    : 2025:07:27 00:08:59
Camera make  : Panasonic
Camera model : DMC-FZ1000
Date/Time    : 2022:11:22 11:08:21
Resolution   : 1806 x 1204
Flash used   : No
Focal length : 146.0mm  (35mm equivalent: 400mm)
Exposure time: 0.0003 s  (1/4000)
Aperture     : f/7.1
ISO equiv.   : 800
Whitebalance : Auto
Metering Mode: pattern
Exposure     : aperture priority (semi-auto)
JPEG Quality : 92
Comment      : Compressed by jpeg-recompress

```

my filter above: yields like 8 lines, all good.

the default view.. yields about 300+ lines, half of them hex-numbered, most other overly-verbose-or-just-bogus data about things noone cares. like TimeSincePowerOn (in hh:mm:ss.ss format)

have a phone? take a photo , download, and analyze it..

**Comment by luebking** [comment]
Thanks.
Fuji, Nikon and Canon also add some noise (notably the proprietary hex fields, but not *that* much) but Panasonic kinda takes the cake it seems (BabyAge1, BabyAge2, BabyName - wtf, there isn't even a Baby in the photo ;))

But "resolution" actually only matches the (localized) value from the phototonic data (thought as much)
I'd probably default to
1. keeping the entire phototonic data segment (so you get to see the file stats + sizes)
2. your filter
3. + artist|copyright|software (photoshop/gimp etc)
4. + lensmodel|isospeedratings|flash|exposureprogram


Does either of you (personal preferences aside) have more suggestions?
GPS data?

**Comment by svilendobrev** [comment]
as long as its editable somewhere - even non-GUI in ~/.config/phototonic/phototonic.conf - it's alright

**Comment by luebking** [comment]
Forgot to tag you, https://github.com/luebking/phototonic/commit/c8e9a46a46cd0ea9bc2516ea6fb4b8775db13180

**Comment by svilendobrev** [comment]
isospeedratings| is repeated

**Comment by svilendobrev** [comment]
what is compact view?

btw, now quite a few exif-items are duplicated. 2 same-but-different focalLength , exposureProgram, 2 same lensmodel and serial, 3 whitebalances, etc. And these differ per camera. i guess some are precooked and others are raw, processing which yields same thing?

**Comment by svilendobrev** [comment]
man, that `[   -   ]` button should ask before deleting the filter irreversibly...

**Comment by luebking** [comment]
1. menu/view/compact thumbs
2. the tags are duplicated in the image exif data, https://github.com/luebking/phototonic/issues/66#issuecomment-3129989089
3. I guess an edit button would be nice; if you've not closed phototonic, the presets are still in  ~/.config/phototonic/phototonic.conf
4. "|nohistogram|" (both bars are required)
